### ISSUE TITLE
OffscreenCanvas is not defined in Next.js

### ISSUE THREAD

**Issue by eiltho** [wcandillon/canvaskit-lite#22]
Hi,

first of all I want to say thank you for creating such a wonderful library to bring Skia to the web.

We'd love to use it for data viz and some animations in a cross-platform RN app.
The project I'm working on is built on solito which is basically Expo for mobile and Next.js for the web part. I tried installing RN Skia with canvaskit-js but I ran into a web error. Everything works as expected in the native app but I get the following error on web

![image](https://github.com/wcandillon/canvaskit-js/assets/131955969/f69e0522-0067-4952-9253-af4e5142db9f)

I understand that SSR might be the issue here but even adding checks such as `typeof window !== "undefined" && typeof window.OffscreenCanvas !== "undefined"` did not help.

I'm wondering if anyone has input or experience of getting this work with Next.js.
This is the `_document.tsx` file where I added the initialization code

![image](https://github.com/wcandillon/canvaskit-js/assets/131955969/e544a8d5-07e5-4a72-806d-2f86c22a2331)

The stacktrace points to the following but I assume it's just the first thing that's evaluated
![image](https://github.com/wcandillon/canvaskit-js/assets/131955969/9f88991e-988d-4208-98ff-40f4a97c10e0)
![image](https://github.com/wcandillon/canvaskit-js/assets/131955969/d1aabb0d-6cba-4270-8b41-b7043a3a7888)

Versions

```
"canvaskit-js": "^2.1.4",
"canvaskit-wasm": "^0.39.1",


Expo SDK 49
Next.js 13.5.6
React 18.2.0
React Native 0.72.4
```

I'd appreciate any support with this 🙏

**Comment by wcandillon** [comment]
Server-side you you will need to fallback to canvaskit-wasm which makes sense since it support headless rendering without browser nor GPU APIs. Is that something that is easily doable in your setup?

**Comment by eiltho** [comment]
We decided to go with a different solution on web for the time being as there's unfortunately not too much time available for this specific topic. We'll revisit the implementation in the future at a more suitable time.
Thank you for your work William 🙏
